language: node_js

node_js:
<<<<<<< HEAD
  - 8
  - 9
  - 10
||||||| 7dcd4e8
  - 6
  - 8
  - 9
  - 10
=======
  - "lts/*"
  - "node"
>>>>>>> 27fa0d715c5a61ee05d40ec9d0b545bc6f7f0326

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: npm release
      node_js: node
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: chase@sillevis.net
        api_key:
          secure: "fPmrr3f1Iw/4mUylzTRuLRC0397z4TJDYzNfSI2BQwFe851EyR1CQv2PQJE2eHC07mxrGZ0i/Fh2F4U5S2u3hSg+qqD0UFzSFXZI//C6b2GG1suld9EVhQBIevPnKTWjT+qitGxsSI82VOIuheQdYmJdFVKcpQOmsqocifGX5XU="
        on:
          tags: true
